#!/bin/bash -e

npm run clean

# need to change path here and in Procfile.dev
DEST_PATH="dist"

mkdir -p $DEST_PATH
touch $DEST_PATH/.nojekyll

tsc
NODE_ENV=production DEST_PATH=$DEST_PATH ./scripts/bundle
node_modules/.bin/pug index.pug -o $DEST_PATH
