#!/bin/bash -ex

# triggers watchify locally and will also be the build script in production

if [ "$NODE_ENV" = "production" ];then
    COMMAND="browserify"
else
    COMMAND="watchify"
fi

eval "node_modules/.bin/$COMMAND app.js -v -o $DEST_PATH/_bundle.js"
